/* "Which answer earns the marks?" scenario questions (Discovery Lab original). */
const FIG = "Fig. 1: rate of photosynthesis is 0 at 0 au light, rises steadily to 40 au, then stays constant up to 100 au.";
const Q = (cw, q, opts, a, tip, ctx) => ({ cw, q, opts, a, tip, ctx });
export const BANK = [
  Q("State", "A question says 'State one function of the stomata' (1 mark). Which answer is best?", ["Gas exchange", "Stomata open and close using guard cells, letting CO2 diffuse in for photosynthesis and water vapour out", "Stomata are found on leaves", "They are very small pores"], 0, "'State' wants one short, precise point. Extra detail earns no extra marks and can contradict yourself."),
  Q("Define", "Which is the best answer to 'Define osmosis' (2 marks)?", ["Water moving from a high to a low concentration", "The net movement of water molecules from a dilute solution to a concentrated solution through a partially permeable membrane", "The movement of particles", "Water moving into cells so they swell"], 1, "A definition needs every key idea: net movement, water, dilute to concentrated (high to low water potential), partially permeable membrane."),
  Q("Describe", "'Describe the trend in Fig. 1.' Which answer earns the marks?", ["Rate rises from 0 to 40 au, then stays constant", "Because chlorophyll absorbs light so the rate rises", "Light intensity is a limiting factor so the rate levels off", "Photosynthesis takes place in the chloroplasts"], 0, "'Describe' = what the data shows, quoting values. Options B and C are explanations: they earn nothing on a Describe question.", FIG),
  Q("Explain", "'Explain why the rate stays constant above 40 au.' Which answer earns the marks?", ["The rate stays constant from 40 to 100 au", "Another factor, such as carbon dioxide or temperature, is now limiting, so more light does not increase the rate", "Plants need light", "It is the maximum on the graph"], 1, "'Explain' = cause + mechanism. Name the limiting factor and link it to the flat line using 'so' or 'because'.", FIG),
  Q("Compare", "Which sentence correctly answers 'Compare arteries and veins' (1 mark)?", ["Arteries have thick walls and veins have valves", "Arteries have thick muscular walls whereas veins have thin walls", "Arteries carry blood away from the heart", "Veins have a large lumen"], 1, "Compare needs BOTH items in one sentence on the SAME feature, joined with 'whereas', 'but' or 'than'."),
  Q("Calculate", "A seedling's mass rises from 20 g to 23 g. Calculate the percentage increase.", ["13%", "15%", "3%", "0.15%"], 1, "Percentage change = (change / original) x 100 = (3 / 20) x 100 = 15%. Always divide by the ORIGINAL value, and show working."),
  Q("Suggest", "Fish die after fertiliser runs into a lake. The question says 'Suggest why'. Which answer earns the mark?", ["The fish died", "Eutrophication: algae grow fast then die, bacteria decompose them and use up the oxygen, so fish suffocate", "The definition of eutrophication is excess nutrients", "Fertiliser is a chemical"], 1, "'Suggest' means apply what you know to a new context. Link known biology (decomposers, oxygen) to the situation given."),
  Q("Evaluate", "'Evaluate whether organic or inorganic fertiliser is better for a farmer' (4 marks). Which answer style earns full marks?", ["A list of facts about inorganic fertiliser only", "Benefits and drawbacks of BOTH, finishing with a judgement using evidence", "A definition of each fertiliser", "'I think inorganic because it is best'"], 1, "'Evaluate' always ends with a judgement backed by the evidence you weighed. No judgement, no top marks."),
  Q("Discuss", "What must a 'Discuss' answer contain?", ["One detailed explanation", "Points from different sides of the issue", "A single-word answer", "A calculation"], 1, "'Discuss' = balanced points on different aspects or sides. You may also reach a conclusion, but breadth comes first."),
  Q("Justify", "You chose to use a greenhouse. What does 'Justify your choice' require?", ["Restating your choice", "Giving evidence or reasoning that supports the choice", "Listing other choices", "Describing the greenhouse"], 1, "'Justify' = 'because the evidence shows...'. Always attach reasoning to the decision."),
  Q("Predict", "Rate increases by 10 units every 10 C from 10 C to 40 C. 'Predict the rate at 30 C' - which answer shows the skill?", ["It will be fast", "30 units, following the pattern of 10 units per 10 C", "Enzymes work faster when warm", "I cannot predict this"], 1, "'Predict' = use the pattern in the data to give a value or outcome, not a vague guess."),
  Q("Describe", "'Describe how to test a leaf for starch' (3 marks). What makes a strong answer?", ["A reason for each step", "Ordered steps: boil the leaf, soften in hot ethanol, rinse, add iodine, blue-black means starch", "Only the final colour", "A definition of starch"], 1, "Describing a method = the ordered actions and the result. You do not need to explain why each step works unless the question says so."),
  Q("Explain", "An 'Explain' question is worth 3 marks. What should your answer usually contain?", ["Three unconnected facts", "Three linked points, each leading to the next with 'because' or 'so'", "A long introduction", "One point repeated three ways"], 1, "Explain marks are usually a chain: cause -> mechanism -> effect. Write it as a linked sentence, not a list."),
  Q("Design", "Which is the most important thing to include in a plan that investigates how light intensity affects plant growth?", ["A fact about chlorophyll", "What you will change, what you will measure, and what you will keep the same", "A conclusion you expect", "A drawing of the plant"], 1, "A plan needs the independent variable, dependent variable, control variables, equipment and repeats. Build that checklist into every plan you write."),
  Q("Design", "In a 6-mark 'Plan an investigation' answer, what should come BEFORE writing the steps?", ["The conclusion", "Identify the independent and dependent variables", "The risk assessment only", "The graph"], 1, "Decide what you change and what you measure first, then the steps flow naturally from that."),
  Q("Design", "A plan changes the light, the temperature and the amount of water all at once. What is wrong?", ["Nothing", "It is not a fair test, since more than one variable changes", "It uses too little equipment", "It has too many repeats"], 1, "Fair test = change ONE variable, control the rest. Otherwise you cannot tell which variable caused the result."),
  Q("Design", "Why should you repeat an investigation and calculate a mean?", ["To make it look longer", "To spot anomalies and make the result more reliable", "To change the independent variable", "Because the examiner expects three trials"], 1, "Repeats improve reliability; a mean reduces the effect of random error. Say WHY, not just 'for accuracy'."),
  Q("Identify", "'Identify the anomalous result' in a table of repeated measurements. What do you write?", ["The mean", "The result that does not fit the pattern", "The highest result", "An explanation for every result"], 1, "'Identify' = pick it out, nothing more. Quote the value exactly as in the table."),
  Q("Complete", "A table has a blank cell. The command word is 'Complete'. You are not sure of the answer. What should you do?", ["Leave it blank", "Write your best answer - a blank can never score", "Cross it out", "Draw a line"], 1, "Blank = 0. A sensible guess might score. Never leave a blank in a 'Complete' question."),
  Q("Show that", "'Show that the magnification is x40.' Image 8 mm, real size 0.2 mm. What earns the marks?", ["x40", "8 / 0.2 = 40, so magnification is x40", "Magnification is how big something looks", "0.2 / 8 = 0.025"], 1, "The answer is given, so the working is the answer. Always write the calculation, then the result."),
  Q("Plot", "Which is essential when you 'Plot' a graph of results?", ["A coloured title", "Labelled axes with units and accurately placed points", "Joining the dots with a ruler", "A key for every point"], 1, "Axis labels with units + points plotted accurately. Then a line of best fit only if the data supports one."),
  Q("Estimate", "'Estimate the rate at 25 C' from a graph with readings at 20 C and 30 C. What does 'Estimate' mean?", ["Guess randomly", "Use the data to work out an approximate value, for example by reading between the two points", "Give the exact value from the table", "Say it is not possible"], 1, "Estimate = an approximate value based on evidence. Show how you got it (read across from the graph, or halfway between)."),
  Q("Determine", "'Determine the optimum temperature' from a graph. What is the answer?", ["The temperature at the highest point of the curve", "The temperature where the rate is 0", "Any temperature on the graph", "The highest temperature on the x-axis"], 0, "'Determine' = work it out from the data. The optimum is the peak of the curve; state the value with its unit."),
  Q("Describe", "You are asked to 'Describe the difference between X and Y'. Which is correct?", ["Give reasons for the difference", "State what is different, with no reasons", "Write everything you know about X", "Evaluate which is better"], 1, "Describing a difference = state it using comparative language. Reasons are only needed if the question says 'Explain'."),
  Q("Explain", "Which word signals that you are explaining rather than describing?", ["'because'", "'then'", "'also'", "'and'"], 0, "Causal connectives - because, so, therefore, which means - are the fingerprint of an Explain answer."),
  Q("Suggest", "A 'Suggest' question has no single correct answer. What should you do?", ["Leave it blank", "Apply relevant biology logically to the situation given", "Give the textbook definition", "Write a long essay"], 1, "Examiners accept any valid, reasoned suggestion. Use what you know and connect it to the new context."),
  Q("Evaluate", "Which sentence is a judgement, suitable for an 'Evaluate' answer?", ["Method A took 10 minutes", "Overall, method A is better because it gave less variable results despite taking longer", "Method B uses a thermometer", "Both use water"], 1, "A judgement words the conclusion ('overall', 'therefore') and points to the evidence that supports it."),
  Q("Name", "'Name the process by which water vapour leaves the leaf.' Best answer?", ["The water goes out through stomata by diffusion during the day to cool the leaf", "Transpiration", "Evaporation and diffusion and cooling", "It is a type of plant process"], 1, "'Name' = the exact term. Do not describe it when a single word answers the question."),
  Q("Describe", "Which is a good way to describe a graph with two variables?", ["Quote specific values from the axes and say how the line changes", "Say it goes up", "Explain the biology", "Describe only the title"], 0, "Always quote figures and units: 'rises from 2 to 8 units between 10 and 30 C'. General words like 'up' gain no mark.")
];
