/* OceanCurrents natural weather — port of weatherPatterns.ts (v3 of the supplied simulator).
   A 10-day coastal weather cycle replaces the old "Test Weather" buttons: every simulated day has its own
   wind, wave height, wave period, tidal strength and cloud cover, repeating from Day 11. */
import { getLang } from "../../../../../../engine/i18n.js?v=9";
const L = (en, es) => (getLang() === "es" ? es : en);

const CYCLE = [
  { id: "sunny", icon: "☀️", name: ["Sunny & Fair", "Soleado y despejado"], desc: ["Clear skies with a gentle ocean breeze.", "Cielo despejado con una suave brisa marina."], sum: ["Great for floating solar and steady wave buoys.", "Ideal para la solar flotante y las boyas de olas constantes."], windSpeedKts: 12.5, waveHeightM: 1.2, wavePeriodSec: 6.2, tidalMultiplier: 1.0, solarEfficiency: 1.0, isStorm: false },
  { id: "breeze", icon: "🌬️", name: ["Fresh Coastal Breeze", "Brisa costera fresca"], desc: ["Rising offshore winds and building chop.", "Vientos de mar adentro en aumento y marejadilla."], sum: ["Wind turbines spin fast; waves start building.", "Las turbinas eólicas giran rápido; las olas empiezan a crecer."], windSpeedKts: 21.0, waveHeightM: 2.0, wavePeriodSec: 7.1, tidalMultiplier: 1.1, solarEfficiency: 0.9, isStorm: false },
  { id: "storm", icon: "🌧️", name: ["Ocean Swell Storm", "Tormenta con oleaje"], desc: ["A low-pressure storm front rolls into Pacifica Bay.", "Un frente de bajas presiones entra en Pacifica Bay."], sum: ["Huge waves & high winds! Solar drops, wave buoys peak.", "¡Olas enormes y vientos fuertes! La solar cae y las boyas llegan al máximo."], windSpeedKts: 31.0, waveHeightM: 4.0, wavePeriodSec: 9.8, tidalMultiplier: 1.15, solarEfficiency: 0.05, isStorm: true },
  { id: "overcast", icon: "☁️", name: ["Overcast & Calming", "Nublado y en calma"], desc: ["Storm clears into cool gray clouds and slack wind.", "La tormenta se aleja y quedan nubes grises y viento flojo."], sum: ["Wind drops and solar is low. Tests your tidal & baseload power!", "El viento baja y la solar rinde poco. ¡Pone a prueba tu energía de mareas y base constante!"], windSpeedKts: 7.5, waveHeightM: 1.8, wavePeriodSec: 7.5, tidalMultiplier: 0.95, solarEfficiency: 0.25, isStorm: false },
  { id: "spring", icon: "🌙", name: ["Spring Tide Surge", "Marea viva intensa"], desc: ["Sun and Moon align in a full lunar spring tide.", "El Sol y la Luna se alinean en una marea viva."], sum: ["Rapid underwater tidal currents give maximum turbine power.", "Las rápidas corrientes submarinas dan la máxima potencia a las turbinas."], windSpeedKts: 14.0, waveHeightM: 1.4, wavePeriodSec: 6.5, tidalMultiplier: 1.5, solarEfficiency: 0.9, isStorm: false },
  { id: "swell", icon: "🌊", name: ["Rolling Ocean Swell", "Oleaje oceánico largo"], desc: ["Deep ocean groundswells roll in from far offshore.", "Mares de fondo llegan desde muy lejos de la costa."], sum: ["Big ocean rollers pump continuous power into wave generators.", "Los grandes rodillos del océano dan energía continua a los generadores de olas."], windSpeedKts: 16.5, waveHeightM: 3.1, wavePeriodSec: 8.9, tidalMultiplier: 1.05, solarEfficiency: 0.85, isStorm: false },
  { id: "doldrums", icon: "🌫️", name: ["Summer Doldrums", "Calmas de verano"], desc: ["Warm, calm, glassy seas with almost no surface wind.", "Mar cálido, en calma y como un espejo, casi sin viento."], sum: ["No wind and small waves! Your 24/7 OTEC & battery keep the lights on.", "¡Sin viento y con olas pequeñas! Tu OTEC 24/7 y las baterías mantienen la luz."], windSpeedKts: 3.2, waveHeightM: 0.7, wavePeriodSec: 5.0, tidalMultiplier: 0.75, solarEfficiency: 1.0, isStorm: false },
  { id: "trade", icon: "🌤️", name: ["Crisp Trade Winds", "Alisios frescos"], desc: ["Steady, reliable sea breeze under partly cloudy skies.", "Brisa marina constante y fiable con cielo parcialmente nublado."], sum: ["Balanced generation across wind, solar, and waves.", "Generación equilibrada entre viento, sol y olas."], windSpeedKts: 18.0, waveHeightM: 1.7, wavePeriodSec: 6.8, tidalMultiplier: 1.0, solarEfficiency: 0.95, isStorm: false },
  { id: "gale", icon: "🌬️", name: ["Choppy Coastal Gale", "Temporal costero con marejada"], desc: ["Brisk coastal gusting creates whitecaps across the bay.", "Rachas costeras fuertes levantan olas con espuma en la bahía."], sum: ["Great wind turbine generation day and night.", "Gran generación eólica de día y de noche."], windSpeedKts: 24.5, waveHeightM: 2.4, wavePeriodSec: 7.6, tidalMultiplier: 1.1, solarEfficiency: 0.75, isStorm: false },
  { id: "lunar", icon: "🌙", name: ["Lunar Peak Current", "Corriente lunar máxima"], desc: ["Gravitational alignment creates fast subsea stream velocity.", "La alineación gravitatoria crea corrientes submarinas rápidas."], sum: ["Subsea tidal turbines generate peak clean megawatts.", "Las turbinas submarinas de marea generan sus máximos megavatios limpios."], windSpeedKts: 13.0, waveHeightM: 1.3, wavePeriodSec: 6.0, tidalMultiplier: 1.4, solarEfficiency: 1.0, isStorm: false },
];

export const CYCLE_LENGTH = CYCLE.length;
export function getWeatherForDay(day) {
  const w = CYCLE[Math.max(0, (day - 1) % CYCLE.length)];
  return { ...w, day, name: L(w.name[0], w.name[1]), description: L(w.desc[0], w.desc[1]), studentSummary: L(w.sum[0], w.sum[1]) };
}
export function getUpcomingForecast(day, count = 4) { return Array.from({ length: count }, (_, i) => getWeatherForDay(day + i)); }
