#!/usr/bin/env python3
"""
Regenerate every navigation shell from data/subjects.json.

Navigation markup is never hand-written. Edit subjects.json, run this, commit.

    python tools/build-nav.py

Creates <node path>/index.html for every non-simulation node, and reports any
folder that used to be a nav page but no longer appears in the tree (it never
deletes anything itself - activity folders live in these directories too).
"""

import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
DATA = REPO / "data" / "subjects.json"
MARKER = "<!-- generated by tools/build-nav.py - do not edit by hand -->"

SHELL = """<!DOCTYPE html>
{marker}
<html lang="en" data-theme="{theme}" data-age-band="{band}" data-tint="paper" data-text-size="m">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} &mdash; Discovery Lab</title>
<link rel="stylesheet" href="{root}engine/style.css?v={v}">
</head>
<body>
<a class="skip-link" href="#main">Skip to content</a>
<header class="site-head">
  <div class="shell site-head__inner">
    <a class="wordmark" href="{root}">
      <svg viewBox="0 0 64 64" aria-hidden="true">
        <circle cx="32" cy="32" r="27" fill="none" stroke="currentColor" stroke-width="1.5" opacity=".28"/>
        <circle cx="32" cy="32" r="19" fill="none" stroke="currentColor" stroke-width="1.5" opacity=".18"/>
        <g stroke="currentColor" stroke-width="1.5" opacity=".45"><path d="M32 2v7M32 55v7M2 32h7M55 32h7"/></g>
        <path d="M32 32 A27 27 0 0 1 53 21" fill="none" stroke="var(--accent)" stroke-width="2.5" stroke-linecap="round"/>
        <circle cx="45" cy="22" r="5" fill="var(--signal)"/>
        <circle cx="32" cy="32" r="2.5" fill="currentColor"/>
      </svg>
      <span class="wordmark__text">Discovery&nbsp;Lab</span>
    </a>
    <a class="eyebrow" href="{root}about/" style="text-decoration:none">About Mr&nbsp;Guevara</a>
  </div>
</header>
<main id="main" class="shell">
  <div id="nav-root" data-path="{path}" data-root="{root}"></div>
</main>
<footer class="site-foot">
  <div class="shell site-foot__inner">
    <span>Discovery Lab &mdash; <a href="{root}about/">{owner}</a></span>
    <span>Your work stays in your browser.</span>
  </div>
</footer>
<script type="module" src="{root}engine/nav.js?v={v}"></script>
</body>
</html>
"""

ASSET_VERSION = "7"


def walk(nodes, trail, out):
    for node in nodes:
        if node.get("type") == "simulation":
            continue
        path = trail + [node["id"]]
        out.append((path, node))
        walk(node.get("children", []), path, out)


def main():
    if not DATA.exists():
        sys.exit(f"missing {DATA}")
    data = json.loads(DATA.read_text(encoding="utf-8"))
    owner = data.get("site", {}).get("owner", "Discovery Lab")

    pages = []
    walk(data["tree"], [], pages)

    written = []
    for path, node in pages:
        folder = REPO.joinpath(*path)
        folder.mkdir(parents=True, exist_ok=True)
        target = folder / "index.html"
        target.write_text(
            SHELL.format(
                marker=MARKER,
                theme=node.get("theme", "earth"),
                band=node.get("ageBand", "secondary"),
                title=node["name"],
                root="../" * len(path),
                path="/".join(path),
                owner=owner,
                v=ASSET_VERSION,
            ),
            encoding="utf-8",
        )
        written.append("/".join(path))

    # Flag generated pages whose node has gone from the tree. Reported, never
    # auto-deleted: activity folders share these directories.
    known = set(written)
    orphans = []
    for f in REPO.rglob("index.html"):
        if ".git" in f.parts:
            continue
        rel = f.relative_to(REPO).parent.as_posix()
        if rel == ".":
            continue
        if MARKER in f.read_text(encoding="utf-8") and rel not in known:
            orphans.append(rel)

    print(f"wrote {len(written)} navigation pages:")
    for w in written:
        print(f"  /{w}/")
    if orphans:
        print("\nno longer in subjects.json - delete these folders by hand:")
        for o in orphans:
            print(f"  /{o}/")


if __name__ == "__main__":
    main()
